w7d3/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :bands

end

w7d3/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w7d3/music_app/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true 
end

w7d3/music_app/app/models/user.rb
class User < ApplicationRecord
    validates :email, :password_digest, :session_token, presence: true 
    validates :email, :session_token, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true }

    before_validation :ensure_session_token
    attr_reader :password

    def self.find_by_credentials(email, password)
        @user = User.find_by(email: email)
        if @user && @user.is_password?(password)
            @user
        else
            nil
        end
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

end

w7d3/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :logged_in?
    helper_method :require_log_in

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_log_in
        redirect_to new_session_url unless logged_in?
    end

    def logged_in?
        !!current_user
    end

    def log_in_user!(user)
        #User.find_by_credentials()
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end
end

w7d3/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_url(@band)
        else
            flash.now[:errors] = ["Name can't be blank"]
            render :new
        end
    end
    
    def new
        render :new
    end

    def edit
        @band = Band.find(params[:id])
        if @band 
            render :edit 
        end
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def update
        @band = Band.find(params[:id])
        if @band.update(name: band_params[:name])
            redirect_to band_url(@band)
        else
            flash.now[:errors] = ["Name can't be blank."]
            render :edit
        end
    end

    def destroy
        @band = Band.find(params[:id]).destroy
        redirect_to bands_url
    end

    def band_params
        params.require(:band).permit(:name)
    end
end

w7d3/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:email],
                                        params[:user][:password])
        if @user
            log_in_user!(@user)
            redirect_to user_url(@user.id)
        else
            redirect_to new_session_url
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
    
end

w7d3/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_log_in, only: [:show]
    def new
        render :new
    end

    def create
        @user = User.new(users_params)
        if @user.save
            log_in_user!(@user)
            redirect_to user_url(@user)
        else
            redirect_to new_user_url
        end
    end

    def show
        @user = User.find(params[:id])
        if @user
            render :show
        else
            redirect_to new_user_url
        end
    end

    private
        def users_params
            params.require(:user).permit(:email, :password)
        end
end

w7d3/music_app/app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        "<input type='hidden' name='authenticity_token' value='#{h(form_authenticity_token)}'>".html_safe
    end
end

w7d3/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

w7d3/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

w7d3/music_app/app/helpers/users_helper.rb
module UsersHelper
end

w7d3/music_app/app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %>'s Name:</h1>
<form action="<%= band_url(@band) %>" method="POST">
    <%= auth_token %>
    <input type="hidden" name="_method" value="PATCH">
    <div>
        <label for="band_name">Band Name:</label>
        <input type="text" name="band[name]" value="">
    </div>
    <div>
        <input type="submit" value="Submit">
    </div>
</form>

w7d3/music_app/app/views/bands/index.html.erb
<% @bands.each do |band| %>
    <ul>
        <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
    </ul>
<% end %>

w7d3/music_app/app/views/bands/new.html.erb
<h2>NEW BAND!</h2>
<form action="<%= bands_url %>" method="POST">
    <%= auth_token %>
    <label for="band_name">Name: </label>
    <input type="text" name="band[name]" id="band_name">
    <input type="submit" value="Submit">
</form>

w7d3/music_app/app/views/bands/show.html.erb
<%= @band.name %>

<form action="<%= band_url(@band) %>" method="POST">
    <%= auth_token %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Destroy Band">
</form>

w7d3/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="nav">
        <h1>Music App</h1>
      </div>
    </header>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="POST">
      <%= auth_token %>
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Log Out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Log In</a>
      <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>
    <% if flash[:errors] %>
      <% flash[:errors].each do |error|%>
        <%= error %>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

w7d3/music_app/app/views/users/new.html.erb
<form action="<%= users_url %>" method="POST">
    <%= auth_token %>
    <div>
        <label for="email">Enter your email:</label>
        <input type="text" name="user[email]" value="" id="email">
    </div>
    <div>
        <label for="password">Enter your password:</label>
        <input type="password" name="user[password]" value="" id="password">
    </div>
    <div>
        <input type="submit" value="Sign Up">
    <div>
</form>

w7d3/music_app/app/views/users/show.html.erb
<h1>Welcome, <%= current_user.email %></h1>